### ISSUE TITLE
refactor: all components [MILESTONE I]

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#2381]
# MILESTONE I

## Angular 7.0

- [x] support angular 7.0 #2372 

## Core
  - [x] DOM handler
     - [x] better scrollbar mesurement  [ngx-bootstrap](https://github.com/valor-software/ngx-bootstrap/blob/development/src/modal/bs-modal.service.ts#L174)  [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/util/scrollbar.ts) [bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L495)
     - [x] `NzStringTemplateOutletDirective` #2481 
  - [x]  schemantics
     - [x] refactor schematics #2602
  - [x] tslint
     - [x] more strict tslint #2372 
  - [x] animation
     - [x] reuseable animation
     - [x] css animation => web animation
     - [x] support disable animation #2922 

## Performance
   - [x] add encapsulation: ViewEncapsulation.None to none css patched component
   - [x] all components except object/array input should work on ChangeDetectionStrategy.OnPush #680 

## Feature
  - [x] sync features with antd react version
  - [x] new components(countdown, statistic, empty, comment)
  - [x] cdk 7.0 new feature
     - [x] Virtual Scroll
     - [x] replace match-media with cdk BreakpointObserver #2500 
     - [x] context menu

## Issue / Bug
- [x] clear / issue /  bug /  feature request /

## Break Change
-  all components OnPush (like `nz-checkbox-group`) mutate won't work
- `nz-input` search suffix -> addon
- `nz-select` `nzDropdownMatchSelectWidth`meaning reverse

# Component TODO List

@cipchk

  - [x] affix #2544 
  - [x] anchor #2546 
  - [x] back-top #2547 
  - [x] list #2548 
  - [x] transfer #2553 
  - [x] upload #2555 
  - [x] tag #2606

@simplejason

  - [x] tree
  
@wilsoncook

  - [x] calendar
  - [x] date-picker
  - [x] time-picker

@wendzhue

  - [x] breadcrumb #2513 
  - [x] cascader #2516
  - [x] icon #2517 #2641 
  - [x] skeleton #2514
  - [x] steps #2512
  - [x] timeline #2515
  - [x] slider #2817 
  - [x] message #2613
  - [x] notification #2613
  - [x] popconfirm #2658
  - [x] popover #2658
  - [x] tooltip #2658
  - [x] carousel #2699 
  - [x] rate #2794
  - [x] progress #2844 

@HsuanXyz

  - [x] auto-complete #2505
  - [x] mention #2510
  - [x] tree-select #2528
  - [x] avatar #2536 
  - [x] drawer #2867 
  - [ ] modal
  

@vthinkxie

  - [x] alert #2372 
  - [x] badge #2372 
  - [x] button #2372 
  - [x] card #2372 
  - [x] checkbox #2478 
  - [x] collapse #2481 
  - [x] divider #2482 
  - [x] form #2493 
  - [x] grid #2498 
  - [x] layout #2500 
  - [x] radio #2519 
  - [x] spin #2530 
  - [x] switch #2533 
  - [x] input #2593 
  - [x] input-number #2601 
  - [x] tabs #2678 
  - [x] select #2741 
  - [x] pagination #2802 
  - [x] menu #2816 
  - [x] dropdown #2816 
  - [x] table #2862 

## Next

Milestone II #2474

**Comment by wendzhue** [comment]
Virtual scroll could and should be applied to the following components:

- [ ] table
- [ ] list
- [ ] tabs
- ...

**Comment by krokofant** [comment]
Which (if any) or these are intended to be done before v7 comes out of rc?

**Comment by vthinkxie** [comment]
@krokofant 7.0 will be released before 02/28

**Comment by powermax01** [comment]
Wait for this so long.

**Comment by dasoncheng** [comment]
I'm waiting

**Comment by vthinkxie** [comment]
done
