### ISSUE TITLE
refactor: all components [MILESTONE II]

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#2474]
# MILESTONE II

## ng-zorro-antd 8.0
  - [x] Sync with ant design latest less @vthinkxie 
  - [x] dropdown same as popover popconfirm @vthinkxie 
  - [x] menu better api @vthinkxie 
  - [x] Support Angular 8 @hsuanxyz 
  - [x] Remove repeated codes in (especially spec) files. Introduce code quality tools (bots). 
  - [x] Replace Chinese comments with English ones. @wendzhue #3552
  - [x] warning deprecated(including icon) & global loging sys @wendzhue #3538
  - [x] SSR #3295 @hsuanxyz 
  - [x] more strict tslint @wendzhue  #2884 #2959 #2960 #2977
  - [x] standalone/secondary entry modules @wendzhue  #3234, close #700
  - [x] exportAs #2417
  - [x] code formatter: prettier @wendzhue #3129 

ref #2381

**Comment by DreamPWJ** [comment]
I wanted to provide web components based on web standards and tired of js frameworks building their own wheels

**Comment by MJomaa** [comment]
@DreamPWJ Angular and Vue are quite close in this regard. It's just React that has a different philosophy.

**Comment by DreamPWJ** [comment]
@MJomaa Yes I mean a set of UI component libraries for React Angular Vue and even native JS that require web component support like ionic has done but ionic doesn't support desktop UI aesthetics and interaction well Chinese needs need to change a lot

**Comment by JohnnieLi** [comment]
STILL WAITING SSR feature from 2018.  Good work anyway, keep up!
