### ISSUE TITLE
feat: support global config

### ISSUE THREAD

**Issue by wendzhue** [NG-ZORRO/ng-zorro-antd#3598]
# feat: support global config 支持全局配置项

## 给小伙伴们的开发指南

如果你的组件需要支持全局配置项，你应该：

- [ ] 确保你的组件已依赖到 `NzConfigService` 上
- [ ] 给 `NzConfig` 接口增加你组件所支持的全局配置项
- [ ] 静态配置项：至少要支持静态配置，将全局配置项和和原来老的配置项（如果有）合并，对于指令和组件来说，你可以使用 `PropWithConfig` 装饰器。
- [ ] 动态配置项：可以选择支持动态配置，监听 `NzConfigService` 的 `configUpdated$` 事件，并在你的组件被更新时触发重渲染等等
- [ ] 修改组件文档并（在 9.0.0 中）弃用老的配置项，注意给出弃用警告

请按[这个清单](https://github.com/NG-ZORRO/ng-zorro-antd/pull/3581/files)处理你负责的组件。

#3613

## List

> 一些组件可能无需支持，请用 🤔 标识

> Some components that don't need global config would be marked with `🤔`.

- [x] Affix @cipchk
- [x] Alert @vthinkxie
- [x] Anchor @cipchk
- [x] AutoComplete @hsuanxyz 🤔 
- [x] Avatar @hsuanxyz
- [x] BackTop @cipchk
- [x] Badge @hsuanxyz
- [x] Breadcrumb @wendzhue 🤔 
- [x] Button @vthinkxie
- [x] Empty @wendzhue
- [x] Calendar @wenqi73 🤔 
- [x] Card @vthinkxie
- [x] Carousel @wendzhue
- [x] Cascader @wendzhue
- [x] Comment @hsuanxyz 🤔
- [x] Checkbox @vthinkxie 🤔
- [x] Collapse @vthinkxie
- [ ] DatePicker @wenqi73 ❌ blocked because year picker and others share config
- [x] Divider @vthinkxie 🤔
- [x] Descriptions @wendzhue
- [x] Drawer @hsuanxyz
- [ ] Dropdown @vthinkxie ❌ there is an inheritance
- [x] Form @vthinkxie
- [x] Grid @vthinkxie
- [x] Icon @wendzhue
- [ ] Input @vthinkxie
- [ ] InputNumber @vthinkxie
- [ ] Layout @vthinkxie
- [ ] List @cipchk
- [x] Mention @hsuanxyz  🤔
- [ ] Menu @vthinkxie
- [x] Message @wendzhue
- [x] Modal @hsuanxyz
- [x] Notification @wendzhue
- [x] PageHeader @hsuanxyz  🤔
- [ ] Pagination @vthinkxie
- [ ] Popconfirm @wendzhue ❌ blocked
- [ ] Popover @wendzhue ❌ blocked
- [x] Progress @wendzhue
- [x] Radio @vthinkxie 🤔
- [x] Rate @wendzhue
- [ ] Select @vthinkxie
- [x] Slider @wendzhue 🤔
- [ ] Spin @vthinkxie
- [x] Statistic @wendzhue 🤔
- [ ] Steps @hsuanxyz
- [x] Skeleton @wenqi73 🤔
- [x] Switch @vthinkxie
- [x] Table @vthinkxie
- [x] Tabs @vthinkxie
- [x] Tag @hsuanxyzx 🤔
- [x] TimePicker @wenqi73
- [x] Timeline @wendzhue 🤔
- [ ] Tooltip @wendzhue ❌ blocked by refactoring to remove the old API. Component lifecycle things.
- [x] Transfer @cipchk 🤔
- [x] Tree @simplejason
- [x] TreeSelect @hsuanxyz
- [x] Typography @hsuanxyz
- [x] Upload @cipchk 🤔

**Comment by wendzhue** [comment]
Closed by #3613
