### ISSUE TITLE
MILESTONE: LATE 2019

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#3667]
MILESTONE: MID 2019

- [x] MILESTONE: LATE 2018 #2381 
- [x] MILESTONE: EARLY 2019 #2474

## Angular / Angular CLI
  - [x] Ivy @hsuanxyz 
  - [x] ng update @hsuanxyz 
  - [ ] support bazel build https://github.com/angular/angular/issues/31310

## Build
  - [x] refactor build scripts @hsuanxyz 

## Components
  - [ ] move more components into ng-zorro-antd #3701 
  - [ ] pipe, rxjs operator package (standalone?)
  - [x] make secondary module default in demo and docs
  - [x] global configuration #2924 @wendellhu95 
  - [ ] global Input type check @vthinkxie [ensure](https://github.com/TradeMe/ensure ) [ast transform](https://blog.angularindepth.com/converting-typescript-decorators-into-static-code-using-tsquery-tstemplate-and-transforms-8c65d606a517)
  - [x] calendar datepicker merge code @wenqi73 
  - [ ] refactor polyfill
  - [ ] refactor util @wendellhu95 
  - [ ] Improve code reuse. `menu`, `mention`, `select`, `datepicker` `calendar` etc.
  - [ ] a11y #1651 
  - [ ] RTL #1762 (discuss)
  - [ ] LTS #2627  (discuss)

## Performance

- [x] Extract a service for `window.resize` events. @wendellhu95
- [x] Global dragging service. [ref](https://github.com/angular/components/blob/master/src/cdk/drag-drop/drag-drop-registry.ts) @wendellhu95 #4350

## Docs
  - [ ] change doc -> custom cli builder @wenqi73 

issues
- bundle size: https://github.com/angular/angular/issues/33881

**Comment by DreamPWJ** [comment]
I want an angular version of pro, which is lightweight, but too heavy for alian

**Comment by CK110** [comment]
> I want an angular version of pro, which is lightweight, but too heavy for alian

`https://github.com/CK110/ant-design-pro-angular`  ant deign pro layout。you can fork it for yourself

**Comment by jacekbartek** [comment]
Do you know about official release date ? We can't wait to release.

**Comment by vthinkxie** [comment]
Hi @jacekbartek , plz track https://github.com/NG-ZORRO/ng-zorro-antd/issues/4634
