### ISSUE TITLE
new components

### ISSUE THREAD

**Issue by wendellhu95** [NG-ZORRO/ng-zorro-antd#3701]
A set of new components (as experimental or enhanced):

- [x] resize @hsuanxyz 
- [ ] g2 (antv g2 wrapper) @wendellhu95 
- [x] code editor (monaco editor wrapper) @wendellhu95  ~~(blocked by tests)~~ #3706
- [x] navigation-tab @wendellhu95 Integrated in tabs #3718
- [ ] time-range @wendellhu95,  blocked by migration of the pipes
- [x] ~~file-read @wendellhu95 ~~ Not necessary. Upload is a better substitution.
- [x] graph #6053 @hsuanxyz 
- [x] pipes (in `core`) @chensimeng

**Comment by duongle26** [comment]
Have you ever considered making a text editor?

**Comment by wendellhu95** [comment]
> Have you ever considered making a rich text editor?

We follow the design spec of Ant Design. Unfortunately, text editor is not included. 

IMHO, rich text editor is too complicated to be in a component library. Try other rich text editors such as Quill, slate or Draft.js, and make it ant-design flavoured using custom CSS. :)
