### ISSUE TITLE
v10 Milestone

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#5034]
# MILESTONE: [NG-ZORRO v10](https://github.com/NG-ZORRO/ng-zorro-antd/milestone/6)

## Angular

- [x] update `@angular/*` to v10 #5571 @hsuanxyz
- [x] strictTemplates support #5006, #4994 @hsuanxyz
- [x] ng-update migrate to v10 @hsuanxyz

## Refactor

- [x] withTransformOriginOn #4959
- [x] refactor `WithConfig` @wendellhu95
- [ ] better naming of APIs @NG-ZORRO/antd
- [ ] try to remove cdk backdrop @NG-ZORRO/antd 
- [ ] dependency injector WebAPI
- [ ] dynamic ng-content projection to ng-template

### Enhancement

- [ ] markForCheck
- [ ] HostListener
- [ ] passive:true
- [ ] avoid layout trashing: https://github.com/wilsonpage/fastdom
- [ ] global style #4447

## Feature

- [ ] RTL support #1762
- [ ] select max tag length #4204
- [ ] tree custom filter #4497 @simplejason
- [ ] tabs `[nzKey]` #2467, drag #3461 @hsuanxyz
- [ ] modal dnd @hsuanxyz
- [ ] change all nz-menu to component @vthinkxie
- [x] #5742

### Bug Fix

- [x] **Style bugs patch**
- [ ] **Tree** @simplejason
  * [x] #4449 
  * [ ] #4566 
  * [ ] #3832
  * [ ] #5736
- [ ] **Carousel** @wendellhu95
  * [ ] #5492
  * [ ] #5051
  * [x] #4292
- [ ] **Badge** @hsuanxyz
  * [ ] animation builder
- [x] **Tags** @hsuanxyz
  * [x] #4581
- [x] **Mention** @hsuanxyz
  * [x] #5722
- [x] **Select** @vthinkxie
  * [x] arrow button not working
- [x] **Table** @vthinkxie
  * [x] border problems
- [ ] **Menu**  @vthinkxie
  * [ ] overflow
- [x] **DatePicker/TimePicker** @wenqi73

### Docs
- [ ] update theme.less if custom theme.less
- [x] use @nguniversal/builders
- [x] external link
- [x] add CN mirror

**Comment by xiaoxiangmoe** [comment]
> refactor WithConfig

这是有什么新的想法吗？

**Comment by wendellhu95** [comment]
> > refactor WithConfig
> 
> 这是有什么新的想法吗？

现在的 API 要把默认值写在 `WithConfig()` 里面，很难看，而且打开 strict property initialization 检查之后之后 TypeScript 还会报错。

重构之后 WithConfig() 也不用带参数了，看起来就跟平常的属性赋值一样。

**Comment by xiaoxiangmoe** [comment]
话说 9.0 是马上要发布了吗？

**Comment by wendellhu95** [comment]
> 
> 
> 话说 9.0 是马上要发布了吗？

已经发布

**Comment by xiaoxiangmoe** [comment]
我指的是 production 版本的。我们已经在用 angular 9 搭配 antd 8 了。

**Comment by xiaoxiangmoe** [comment]
我发现是 cnpm 落后了，我去 sync 一下。

**Comment by wendellhu95** [comment]
> try to remove cdk backdrop

This requires some "click outside" mechanism. We can hack it or file a pull request to CDK.

**Comment by vthinkxie** [comment]
> > try to remove cdk backdrop
> 
> This requires some "click outside" mechanism. We can hack it or file a pull request to CDK.

we need to resolve this issue https://github.com/NG-ZORRO/ng-zorro-antd/issues/4933 before implements click outside mechanism

**Comment by TxOne** [comment]
[#5588](https://github.com/NG-ZORRO/ng-zorro-antd/issues/5588)

**Comment by John0King** [comment]
Will you guys consider change how the new version be used ?
a suggestion:
today  Angular 9.0   zorro  9.x
tomorrow  Angular 10.0    zorro   10.0.x  = 9.x (first support)      10.1.x  =  new  feature

or 

today Angualr 9.0   zorro 9.x
tomorrow  Angular 10.0   zorro    9.99.x         use  10.x   for new feature

**Comment by dylanvdmerwe** [comment]
A nice way could be to have the x.0 release as the release that supports the latest version of Angular.

```
10.0 -> supports Angular 10
11.0 -> supports Angular 11
12.0 -> supports Angular 12
```

Then the x.1 to x.99 releases to have new functionality. 

```
10.1 -> new functionality/bug fixes support on the Angular 10 supported version
10.2 -> new functionality/bug fixes support on the Angular 10 supported version

11.1 ->new functionality/bug fixes support on the Angular 11 supported version
etc.
```

In this way you decouple the effort needed to support new functionality AND a new update in one release.

**Comment by hrvbernardic** [comment]
Hi. When can we expect the new version released?

**Comment by xiaoxiangmoe** [comment]
@hrvbernardic  10.0.0-beta.2 works well for me.
I'm waiting for Angular 11 with ivy language service now. Waiting ng-zorro-antd v11. lol.

**Comment by hrvbernardic** [comment]
@xiaoxiangmoe Same here, not complaining. Using beta 4. Just interested in some fixes on the table component I saw in commits.
