### ISSUE TITLE
V12 update

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#6731]
- [x] Overflow Directive @vthinkxie #6601 
- [x] support reset NZ_CONFIG inside component #6601  
- [ ] Menu Refactor 
- [ ] Tabs Refactor
- [ ] Table Refactor
- [x] Replace tslint with eslint @yangjunhan 
- [x] husky & lintstage @yangjunhan 
- [x] Upgrade to angular v12 @hsuanxyz
- [ ] [NG-ZORRO/schematics](https://github.com/NG-ZORRO/schematics) update husky and migrate to ESLint @hsuanxyz 
- [x] Remove deprecated APIs and add migration schematics @hsuanxyz 
- [ ] issues @wenqi73 @hsuanxyz 
- [ ] Refactor nzStringTemplateOutlet @c3Vu 
- [ ] DatePicker ineligible date disabled #6529 
- [ ] DatePicker `ngModelChange` triggered uncorrectly #5908
- [ ] Pull requests @NG-ZORRO/antd 
  * [👀: Review requested PRs](https://github.com/NG-ZORRO/ng-zorro-antd/pulls?q=is%3Aopen+review-requested%3A%40me)

**Comment by maratkalibek** [comment]
Please, also fix this issue #6696

**Comment by duong-le** [comment]
Does v12 come with ivy enabled?

**Comment by NoDocCat** [comment]
TimePicker.RangePicker support
![image](https://user-images.githubusercontent.com/20502666/121329372-bd41d000-c947-11eb-9c53-fcf83ebbd306.png)

**Comment by hoondeveloper** [comment]
and also.. pls fix this issue #6760

**Comment by RoboZoom** [comment]
Hi,  Any idea for when the version 12 update will be released? Thanks!

**Comment by narsiliko** [comment]
Still can`t install antd with angular 12

package.json
```json
  "dependencies": {
    "@angular/animations": "~12.0.3",
    "@angular/common": "~12.0.3",
    "@angular/compiler": "~12.0.3",
    "@angular/core": "~12.0.3",
    "@angular/forms": "~12.0.3",
    "@angular/platform-browser": "~12.0.3",
    "@angular/platform-browser-dynamic": "~12.0.3",
    "@angular/router": "~12.0.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.3",
    "@angular/cli": "~12.0.3",
    "@angular/compiler-cli": "~12.0.3",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "express": "^4.17.1",
    "http-proxy-middleware": "^0.19.1",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "~4.2.3"
  }
```

console
```bash
$ ng add ng-zorro-antd
ℹ Using package manager: npm
✖ Unable to find compatible package.  Using 'latest'.
✖ Package has unmet peer dependencies. Adding the package may not succeed.
 
The package ng-zorro-antd will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular-test3@0.0.0
npm ERR! Found: @angular/animations@12.0.5
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~12.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^11.0.4" from ng-zorro-antd@11.4.2
npm ERR! node_modules/ng-zorro-antd
npm ERR!   ng-zorro-antd@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/narsil/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/narsil/.npm/_logs/2021-07-03T11_13_19_806Z-debug.log
✖ Package install failed, see above.
```

**Comment by maratkalibek** [comment]
Hello! Any ETA here?
