### ISSUE TITLE
MILESTONE: June 2022 🔥 🔥 🔥 

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#7389]
MILESTONE: June

> We need to implement features that are supported by `ant-design` but not supported by `ng-zorro-antd`, so we plan to carry out relevant synchronization work in May and June, we also welcome more people to participate in contributing code! 🔥 🔥 🔥 
> If you want to participate in the development of `ng-zorro-antd`, please leave your comment with information about the component you want to be responsible for 🥇 
> Before you start coding, please make sure you have read [CONTRIBUTING.md](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md
).
Components:
- [x] AutoComplete        **@buqiyuan**
  - [x] support validation status ([demo](https://ant.design/components/auto-complete/#components-auto-complete-demo-status))
- [x] Cascader        **@simplejason**
  - [x] support validation status ([demo](https://ant.design/components/cascader/#components-cascader-demo-status))
  - [x] support placement ([demo](https://ant.design/components/cascader/#components-cascader-demo-placement))
- [x] DatePicker        **@TheBeard30**
  - [x] support validation status ([demo](https://ant.design/components/date-picker/#components-date-picker-demo-status))        **@simplejason**
  - [x] support placement ([demo](https://ant.design/components/date-picker/#components-date-picker-demo-placement))
- [ ] Input      **@ZENETOM**
  - [ ] support loading of search mode ([demo](https://ant.design/components/input/#components-input-demo-search-input-loading))
  - [x] support showing character counting ([demo](https://ant.design/components/input/#components-input-demo-show-count))
  - [x] support validation status ([demo](https://ant.design/components/input/#components-input-demo-status))        **@simplejason**
  - [ ] Demo: [focus with additional option](https://ant.design/components/input/#components-input-demo-focus)
- [x] InputNumber        **@simplejason**
  - [x] support borderless ([demo](https://ant.design/components/input-number/#components-input-number-demo-borderless))
  - [x] support out of range ([demo](https://ant.design/components/input-number/#components-input-number-demo-out-of-range))
  - [x] support validation status ([demo](https://ant.design/components/input-number/#components-input-number-demo-status))
- [ ] Mention
  - [ ] support autosize ([demo](https://ant.design/components/mentions/#components-mentions-demo-autoSize))
  - [x] support validation status ([demo](https://ant.design/components/mentions-cn/#components-mentions-demo-status))        **@simplejason**
- [x] Select       **rorry121**
  - [x] support placement ([demo](https://ant.design/components/mentions/#components-mentions-demo-status))
  - [x] support validation status ([demo](https://ant.design/components/select-cn/#components-select-demo-status))        **@simplejason**
- [x] TimePicker
  - [x] support validation status ([demo](https://ant.design/components/time-picker/#components-time-picker-demo-status))        **@simplejason**
  - [x] support borderless ([demo](https://ant.design/components/date-picker-cn/#components-date-picker-demo-bordered))
- [ ] Transfer
  - [ ] Bug: tree transfer
  - [x] support validation status ([demo](https://ant.design/components/transfer/#components-transfer-demo-status))       **@simplejason**
- [x] TreeSelect      **@JackYumg**
  - [x] support placement ([demo](https://ant.design/components/tree-select/#components-tree-select-demo-placement))
  - [x] support validation status ([demo](https://ant.design/components/tree-select-cn/#components-tree-select-demo-status))
- [ ] Avatar: support [responsive Size](https://ant.design/components/avatar/#components-avatar-demo-responsive)
- [ ] Badge        **@buqiyuan**
  - [ ] support offset ([demo](https://ant.design/components/badge-cn/#components-badge-demo-offset))
- [x] Calendar: support custom header ([demo](https://ant.design/components/calendar/#components-calendar-demo-customize-header))
- [ ] Collapse: support setting position of expand icon ([demo](https://ant.design/components/collapse-cn/#components-collapse-demo-extra))
- [ ] Image: preview a collection from one image ([demo](https://ant.design/components/image/#components-image-demo-preview-group-visible))
- [x] [Segmented](https://ant.design/components/segmented-cn/): New component        **@hullis**  #7404
- [ ] Table
  - [ ] checkbox or radio ([demo](https://ant.design/components/table/#components-table-demo-row-selection))
  - [ ] filter: tree/search/ ([demo](https://ant.design/components/table-cn/#components-table-demo-filter-in-tree))
  - [ ] [order Specific Column](https://ant.design/components/table/#components-table-demo-order-column)
- [ ] Alert        **rorry121**
  - [ ] support loop banner ([demo](https://ant.design/components/alert/#components-alert-demo-loop-banner))
- [ ] Message      **@Benamin**
  - [ ] support setting style and className ([demo](https://ant.design/components/message/#components-message-demo-custom-style))
  - [ ] support updating message by key ([demo](https://ant.design/components/message/#components-message-demo-update))
- [x] Modal: support dragging ([demo](https://ant.design/components/message/#components-message-demo-update))
- [ ] Notification        **rorry121**
  - [ ] support top and bottom placement ([demo](https://ant.design/components/notification/#components-notification-demo-placement))
  - [x] ~~support updating message by key ([demo](https://ant.design/components/notification-cn/#components-notification-demo-placement))~~
- [ ] Popconfirm        **rorry121**
  - [ ] [asynchronously close on Promise](https://ant.design/components/popconfirm/#components-popconfirm-demo-promise)
- [ ] Anchor        **@buqiyuan**
  - [ ] sync new properties ([demo](https://ant.design/components/anchor))
  
Styles:
ref: [#33862](https://github.com/ant-design/ant-design/issues/33862)
- [x] CSS Variables       **@simplejason**
- [ ] CSS in JS

**Comment by JackYumg** [comment]
tree-select
     support placement
     support validation status

**Comment by ZENETOM** [comment]
Input
support loading of search mode
support showing character counting

**Comment by ZENETOM** [comment]
Modal: support dragging

**Comment by Benamin** [comment]
Message
 support setting style and className 
 support updating message by key

**Comment by TheBeard30** [comment]
DatePicker
      support validation status
      support placement

**Comment by whittssg** [comment]
tree-select
fix virtualization so that it works ?

[One of the many references to it not working](https://github.com/NG-ZORRO/ng-zorro-antd/issues/6426)

Thanks

**Comment by rorry121** [comment]
Select
support placement
support validation status

 Notification
support top and bottom placement 
support updating message by key ([it seems already supported in ng-zorro-antd](https://ng.ant.design/components/notification/en#components-notification-demo-update) )

Alert: support loop banner
Popconfirm: asynchronously close on Promise

**Comment by JackYumg** [comment]
@simplejason 
我参与tree-select，自定义状态的功能。
开发过程中对标antd的功能发现，treeSelect是与select使用同一个class。
而在zorro里面实现该功能时是否采用同样的方式。
如果是的话，那么任务有一定的重叠。

**Comment by simplejason** [comment]
> @simplejason 我参与tree-select，自定义状态的功能。 开发过程中对标antd的功能发现，treeSelect是与select使用同一个class。 而在zorro里面实现该功能时是否采用同样的方式复用class。 如果是的话，那么任务有一定的重叠。

默认情况下，tree-select 应该完全集成tree的功能，开发前确认class 一定是和 ant-design 同步的

**Comment by buqiyuan** [comment]
I claim：
- `AutoComplete`
- `Badge`
- `Anchor`

**Comment by JackYumg** [comment]
> > @simplejason 我参与tree-select，自定义状态的功能。 开发过程中对标antd的功能发现，treeSelect是与select使用同一个class。 而在zorro里面实现该功能时是否采用同样的方式复用class。 如果是的话，那么任务有一定的重叠。
> 
> 默认情况下，tree-select 应该完全集成tree的功能，开发前确认class 一定是和 ant-design 同步的
改了之后需要怎么确认代码的正确性和合理性

**Comment by simplejason** [comment]
> @simplejason 改了之后需要怎么确认代码的正确性和合理性
> 
> https://imwuyum.club:447/components/tree-select/zh
> 
> 修改后的效果预览地址

提交 PR 后机器人会自动构建预览环境，同时 CI 会保证能正常构建，基本原则应该是跟随 `ant-design` 的 dom 结构与 css class 样式. ([PR 规范](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr))

---

After submitting the PR, the ng-zorro-bot will automatically build the preview environment, and the CI will run, the basic principle should be to follow the `ant-design` which means dom structure and css class style should be same with `antd`. ([PR specification](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr))

**Comment by JackYumg** [comment]
@simplejason 
ERROR: Permission to NG-ZORRO/ng-zorro-antd.git denied to JackYumg.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


推分支上来没权限？还是推得不对？

**Comment by simplejason** [comment]
> @simplejason ERROR: Permission to NG-ZORRO/ng-zorro-antd.git denied to JackYumg. fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.
> 
> 推分支上来没权限？还是推得不对？

Step 1: fork `ng-zorro-antd`
Step 2:  git clone your own repo `ng-zorro-antd`
Step 3: follow [this documention](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr)

**Comment by simplejason** [comment]
@rorry121 @TheBeard30 Hi guys, I noticed that you haven't implemented the `status` setting feature yet, I hope to take over the development if it hasn't started yet :)

**Comment by rorry121** [comment]
ok, recently I will find time to complete others

**Comment by rorry121** [comment]
> 

ok, recently I will find time to complete others

**Comment by TheBeard30** [comment]
> @rorry121 @TheBeard30 Hi guys, I noticed that you haven't implemented the `status` setting feature yet, I hope to take over the development if it hasn't started yet :)

okay

**Comment by simplejason** [comment]
Hi @TheBeard30 @ZENETOM @rorry121 @JackYumg @buqiyuan @Benamin , 按计划我们将于六月份完成上述大部分工作，七月推出 v14 版本，大家开发过程中有任何疑问可以联系我或在钉钉群沟通（如有需要也可以单独创建微信开发讨论群），感谢各位的帮助 :)

**Comment by TheBeard30** [comment]
好的

**Comment by TheBeard30** [comment]
TimePicker
support borderless

**Comment by JackYumg** [comment]
@simplejason 
![image](https://user-images.githubusercontent.com/62476270/177094579-34190890-eb17-416a-97b1-83b5beeee2c5.png)
因为这个问题一直过不了，但是我没改动过这个呀

**Comment by simplejason** [comment]
> @simplejason ![image](https://user-images.githubusercontent.com/62476270/177094579-34190890-eb17-416a-97b1-83b5beeee2c5.png) 因为这个问题一直过不了，但是我没改动过这个呀

抱歉之前没注意到，这个可以忽略，是命名问题

**Comment by TheBeard30** [comment]
Table
support checkbox or radio 
support filter: tree/search/

**Comment by JackYumg** [comment]
@simplejason 这个在CodeFactor中一直是有这个问题，哪一款我没动过，其实这个功能5月份就写好了的，代码测试也通过了的

**Comment by FOWind** [comment]
@simplejason Is there any plan about https://github.com/NG-ZORRO/ng-zorro-antd/issues/7207 ?

**Comment by Laffery** [comment]
mention
transfer
callendar
collapse

**Comment by sergioorlov** [comment]
Dear developers, what about dnd for columns of table with rows ?

**Comment by scarqin** [comment]
@simplejason
Hi,i will created a PR for：Avatar: support [responsive Size](https://ant.design/components/avatar/#components-avatar-demo-responsive)

**Comment by Laffery** [comment]
close via #9263
