### ISSUE TITLE
NG-ZORRO Roadmap

### ISSUE THREAD

**Issue by simplejason** [NG-ZORRO/ng-zorro-antd#7694]
<p align="center">
⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️
</p>

<div align="center">
<h3>Road Map</h3>
</div>

<p align="center">
⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️
</p>

> All the following tasks will be split into different MILESTONE as soon as possible.

## Tasks

- [ ] Sync with ant-design@5.x, CSS-IN-JS, new components
- [x] Refactor: [standalone components](https://angular.io/guide/standalone-components)
- [x] Refactor: [Typed Forms](https://angular.io/guide/typed-forms)
- [ ] Enhancement

## Milestones

- [ ] [MILESTONE: June 2022(Delayed)](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7389)

We would like to hear any suggestions from the community. Welcome to join in this discussion. ☕️ Just comment in these issues above.

---

Team ng-zorro-antd with ❤️

---

> Note: suggestions accepted and implemented would be folded.

**Comment by rehdie** [comment]
Standalone directives would be cool to enable directive composition...

**Comment by cioina** [comment]
Any idea to move to rxjs 7.x and 8.x-alpha; something like [this](https://github.com/Tinkoff/taiga-ui/commit/0804b745325dd4ea33e3b42b984d771a00a8a3b5)

**Comment by zzhiren** [comment]
冲，css in js预计大概什么时候上线啊~

**Comment by HyperLife1119** [comment]
> Any idea to move to rxjs 7.x and 8.x-alpha; something like [this](https://github.com/Tinkoff/taiga-ui/commit/0804b745325dd4ea33e3b42b984d771a00a8a3b5)

I thought I'd help with this part.

**Comment by wojtek1150** [comment]
I can help with standalone components. Someone already takes this or no?

**Comment by MunMunMiao** [comment]
> I can help with standalone components. Someone already takes this or no?

Welcome to participate

**Comment by Laffery** [comment]
close via #9263
