### ISSUE TITLE
WIP: Support more standalone components

### ISSUE THREAD

**Issue by HyperLife1119** [NG-ZORRO/ng-zorro-antd#8186]
我们需要将部分组件转为 standalone 组件。

值得注意的是，不是**所有**组件都适合改为 standalone，只有那些能够真正被“单独”使用的组件才适合改为 standalone 组件。

例如，grid 功能至少需要 `nz-row` 与 `nz-col` 两个组件才能组合为一个完整功能，因此这两个组件都不应该是 standalone 组件，它们更适合使用一个 NgModule 来将多个组件捆绑为一个功能/特性。

---

We need to convert some components into standalone components.

It is worth noting that not all components are suitable to be changed to standalone. Only those components that can truly be used "individually" are suitable to be changed to standalone components.

For example, the grid feature requires at least `nz-row` and `nz-col` components to be combined into a full feature, so neither of them should be standalone components, they are more suited to use an NgModule to bundle multiple components into a single feature.

经过初步调查，有以下组件适合更改为 standalone：

After preliminary investigation, the following components are suitable for change to standalone:

- [ ] button, button-group
- [x] flex
- [ ] icon
- [ ] typography
- [ ] divider
- [ ] space
- [x] affix
- [ ] pagination
- [ ] cascader
- [ ] checkbox, checkbox-group, checkbox-wrapper
- [ ] color-picker, color-block
- [ ] date-picker, week-picker, month-picker, year-picker, range-picker
- [ ] input, input-group, textarea-count
- [ ] input-number, input-number-group
- [ ] mention
- [ ] radio, radio-group
- [ ] rate
- [ ] slider
- [ ] switch
- [ ] time-picker
- [ ] transfer
- [ ] tree-select
- [ ] upload
- [ ] avatar, avatar-group
- [ ] badge
- [ ] calendar
- [ ] empty
- [ ] image, image-group
- [ ] popover
- [ ] qrcode
- [ ] segmented
- [ ] statistic, countdown
- [ ] tag
- [ ] tooltip
- [ ] tree
- [ ] alert
- [ ] popconfirm
- [ ] progress
- [ ] spin
- [ ] back-top
- [ ] water-mark
